### ISSUE TITLE
Improve transaction usage

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/RealistikGDPS#13]
Currently, there is no transaction usage when working with the MySQL database (or any for that matter). This means that if an error occurs during a request, data may only partially be written. 

This problem extends to transactions between multiple services, with a possible example being a level being added to MySQL but not viewable due to a meili error.

**Comment by cmyui** [comment]
Similar to my comment on #14, my personal recommendation would be to focus on mysql transactions specifically, and consider an asynchronous model for persisting data to other less-critical sources (meilli/s3/etc.).

If you have reason to require that resources are available on one or many of the secondary source(s), a possible solution could be to commit records in an "incomplete" state to mysql, and mark them as "completed" upon success of the asynchronous job. When fetching resources from the database, you can then add an exclusion filter to ensure only fully-persisted records are returned.

This way, you can reduce complexity in the api application code (no longer need to manually handle all potential points of failure and their rollback paths across all data sources - you only need to worry about success in your sql txn and perhaps the spawning of the async job), and your asynchronous jobs can implement much stronger retry policies as they are decoupled from the request-response cycle of the user-initiated API request (and are thus no longer constrained to client limitations such as request timeouts).
