### ISSUE TITLE
Improve S3 redundancy 

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/RealistikGDPS#14]
Currently, if S3 is enabled, it is the only source that RealistikGDPS will fetch data from. This means that in cases where a connection to S3 is lost, saving data will completely fail and the user will be given an error. The S3 service is almost always ran by a third party and therefore it should not be trusted to have 100% uptime.

A solution to this might be to store files locally while S3 is unavailable, using default behaviour for when S3 is disabled.

This will require loading data to account for the possibility that some data may only be present locally.

However, storing data locally that should be in S3 isn't great in the long term. A potential solution to this is automatically uploading any local files to S3 upon retrieval and deleting the local copy. This could also help people gradually transition to S3.

**Comment by cmyui** [comment]
is it possible to background the saving of data to S3 in most cases? that + a strong retry mechanism should be fine imo, if this is a concern

data fetching is also not a solvable problem here (if s3 is the source of truth then you're bound to having to rely on its uptime for retrieval)

**Comment by cmyui** [comment]
> if this is a concern

worth considering what level of complexity is worth adding here for the given level of risk
