### ISSUE TITLE
Incorrect user displayed when downloading a level.

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/RealistikGDPS#15]
Currently, the incorrect user is displayed when opening a level created by another player.

![image](https://github.com/RealistikDash/RealistikGDPS/assets/36131887/5ba913ea-89c9-40e2-bb7a-b3dbc6f31fcf)

This is likely a very simple issue related with response data as the data stored in the database and the object are all correct.
```
Successfully fetched level Level(id=4, name='Level by Test2', user_id=100, ...)
```

**Comment by efwxx** [comment]
might have something to do with the `create_level` object:
```py
gd_obj.dumps(gd_obj.create_level(level_res.level, level_res.data))
``` 
said line can be found [here](https://github.com/RealistikDash/RealistikGDPS/blob/535ce9a9b294f4cc8a5bb6b645b213a637598ea6/rgdps/api/gd/levels.py#L189)

**Comment by RealistikDash** [comment]
Late update:
This issue was likely caused by sending incorrectly formatted user data (used the default user object rather than the simplified one). However, there is another issue occurring preventing the page from loading completely at the moment.

**Comment by RealistikDash** [comment]
Fixed a while ago. Current issue is unrelated.
