### ISSUE TITLE
cant post message?

### ISSUE THREAD

**Issue by how-to-do-frontend** [RealistikDash/RealistikGDPS#33]
title says all, try to post message but it fails

stacktrace:
https://pastebin.com/raw/0WnQs54m

**Comment by RealistikDash** [comment]
@lenforiee

**Comment by lenforiee** [comment]
The error is regarding someone literally not having a username, @how-to-do-frontend could you check in database if recipient have username?

**Comment by RealistikDash** [comment]
Username? Iirc there is no username field in the schema for messages

**Comment by how-to-do-frontend** [comment]
> The error is regarding someone literally not having a username, @how-to-do-frontend could you check in database if recipient have username?

how would they not have a username? they came up in user search so i think they have a username lmao

**Comment by lenforiee** [comment]
My bad, RealistikDash have point, we do not store username in messages table, are you even use newest table found in migration? could i see your message table schema?

**Comment by how-to-do-frontend** [comment]
OH sorry i was using an old message table schema for some reason, nvm!!
