### ISSUE TITLE
Optimise bulk fetching of models from the database.

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/RealistikGDPS#40]
Currently, when multiple models have to be fetched at once, it is done through a look calling the corresponding repository function.
https://github.com/RealistikDash/RealistikGDPS/blob/85bd1a13ad78df1122001b2837b54fb996d14ea6/rgdps/usecases/user_relationships.py#L37-L38

This means that for each entry, a new individual query has to be made, which can add up very quickly. While the individual query is rather fast, it would be possible (and likely optimal) to fetch all of this data at once. 

This issue proposes implementing a `multiple_from_id` function for all of the main resources (such as `Level`, `User`, etc). This option will take a list of object IDs and return all the possible results in a list. It should produce the same result as running the `from_id` function in a loop and ignoring the `None` entries. This means that the order of the entries should be presented in the same way as the input list.

This shouldn't add much complexity and should make working with large batches of objects easier.

**Comment by tsunyoku** [comment]
i'll jump on this one
