### ISSUE TITLE
Fix incorrect total level count.

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/RealistikGDPS#78]
Currently we use meili's "estimated search results" for this figure:
![image](https://github.com/RealistikGDPS/RealistikGDPS/assets/36131887/43751d69-3f67-47c6-af1e-ec36cf027219)
However, this is incorrect for values where more than 1000 results exist. This can be fixed by either querying MySQL (long approach as you have to replicate filters) or somehow fixing meili.

**Comment by 7ez** [comment]
no hablo ingles

**Comment by RealistikDash** [comment]
https://stackoverflow.com/a/74986080

Okay looks like this is just it.
